-- UIU Lost & Found Portal - Supabase schema
-- Run once on a new Supabase project from SQL Editor, or use as a migration.

begin;

create extension if not exists pgcrypto;

create schema if not exists private;
revoke all on schema private from public;

create type public.app_role as enum ('student', 'admin');
create type public.item_type as enum ('lost', 'found');
create type public.approval_status as enum ('pending', 'approved', 'rejected');
create type public.item_status as enum ('open', 'pending_claim', 'match_under_review', 'resolved');
create type public.claim_kind as enum ('ownership', 'recovery');
create type public.claim_status as enum ('pending', 'approved', 'rejected', 'returned');
create type public.match_status as enum ('suggested', 'accepted', 'rejected');
create type public.handover_status as enum ('proposed', 'confirmed', 'complete', 'cancelled');
create type public.dispute_status as enum ('open', 'escalated', 'resolved');

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text not null check (char_length(full_name) between 2 and 100),
  department text not null default 'Not specified' check (char_length(department) <= 120),
  avatar_path text,
  role public.app_role not null default 'student',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Student ID and phone are deliberately separate from public profile data.
create table public.profile_private (
  user_id uuid primary key references public.profiles (id) on delete cascade,
  student_id text not null check (char_length(student_id) between 3 and 40),
  phone text check (phone is null or char_length(phone) between 7 and 25),
  updated_at timestamptz not null default now()
);

create unique index profile_private_student_id_key
  on public.profile_private (lower(student_id));

create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique check (char_length(name) between 2 and 60),
  code text not null unique check (code ~ '^[A-Z0-9]{3,8}$'),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.items (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid not null references public.profiles (id) on delete restrict,
  category_id bigint not null references public.categories (id) on delete restrict,
  type public.item_type not null,
  approval_status public.approval_status not null default 'pending',
  status public.item_status not null default 'open',
  title text not null check (char_length(title) between 2 and 120),
  description text not null check (char_length(description) between 5 and 300),
  location text not null check (char_length(location) between 2 and 160),
  public_location text generated always as (
    case
      when lower(location) like '%cafeteria%' or lower(location) like '%canteen%'
        then 'Cafeteria / Dining Area'
      when lower(location) like '%library%' or lower(location) like '%study%'
        then 'Library & Study Hub'
      when lower(location) like '%room%' or lower(location) like '%lab%' or lower(location) like '%class%'
        then 'Academic Building'
      when lower(location) like '%plaza%' or lower(location) like '%ground%' or lower(location) like '%field%'
        then 'Open Campus Grounds'
      when lower(location) like '%auditorium%' or lower(location) like '%hall%'
        then 'Auditorium & Events Complex'
      else 'UIU Campus Area'
    end
  ) stored,
  occurred_on date not null,
  photo_path text,
  reviewed_by uuid references public.profiles (id) on delete set null,
  reviewed_at timestamptz,
  rejection_reason text check (rejection_reason is null or char_length(rejection_reason) <= 500),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint item_review_consistency check (
    (approval_status = 'pending' and reviewed_at is null)
    or (approval_status in ('approved', 'rejected') and reviewed_at is not null)
  )
);

-- Never put held-back verification details in the public items table.
create table public.item_private_details (
  item_id uuid primary key references public.items (id) on delete cascade,
  reporter_id uuid not null references public.profiles (id) on delete cascade,
  hidden_detail text not null check (char_length(hidden_detail) between 3 and 200),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.claims (
  id uuid primary key default gen_random_uuid(),
  item_id uuid not null references public.items (id) on delete cascade,
  claimant_id uuid not null references public.profiles (id) on delete cascade,
  kind public.claim_kind not null,
  status public.claim_status not null default 'pending',
  match_score smallint check (match_score between 0 and 100),
  admin_note text check (admin_note is null or char_length(admin_note) <= 1000),
  reviewed_by uuid references public.profiles (id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint claim_review_consistency check (
    (status = 'pending' and reviewed_at is null)
    or (status in ('approved', 'rejected', 'returned') and reviewed_at is not null)
  )
);

create unique index one_live_claim_per_user_and_item
  on public.claims (item_id, claimant_id)
  where status in ('pending', 'approved');

-- Claim answers and contact information are only visible to claimant + admins.
create table public.claim_evidence (
  claim_id uuid primary key references public.claims (id) on delete cascade,
  claimant_id uuid not null references public.profiles (id) on delete cascade,
  identifying_feature text not null check (char_length(identifying_feature) between 2 and 300),
  proof text not null check (char_length(proof) between 2 and 500),
  contact_phone text not null check (char_length(contact_phone) between 7 and 25),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.item_matches (
  id uuid primary key default gen_random_uuid(),
  lost_item_id uuid not null references public.items (id) on delete cascade,
  found_item_id uuid not null references public.items (id) on delete cascade,
  score smallint not null check (score between 0 and 100),
  reasons text[] not null default '{}',
  status public.match_status not null default 'suggested',
  created_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (lost_item_id, found_item_id),
  check (lost_item_id <> found_item_id)
);

create table public.conversations (
  id uuid primary key default gen_random_uuid(),
  claim_id uuid not null unique references public.claims (id) on delete cascade,
  item_id uuid not null references public.items (id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.conversations (id) on delete cascade,
  sender_id uuid not null references public.profiles (id) on delete cascade,
  body text not null check (char_length(body) between 1 and 2000),
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.handovers (
  id uuid primary key default gen_random_uuid(),
  claim_id uuid not null unique references public.claims (id) on delete cascade,
  conversation_id uuid not null unique references public.conversations (id) on delete cascade,
  location text not null default 'Student Affairs Desk',
  scheduled_for timestamptz,
  pin_code text not null check (pin_code ~ '^[0-9]{4}$'),
  status public.handover_status not null default 'proposed',
  confirmed_at timestamptz,
  completed_at timestamptz,
  completed_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  title text not null check (char_length(title) between 1 and 120),
  body text not null check (char_length(body) between 1 and 500),
  destination text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.disputes (
  id uuid primary key default gen_random_uuid(),
  item_id uuid not null references public.items (id) on delete cascade,
  status public.dispute_status not null default 'open',
  reason text check (reason is null or char_length(reason) <= 1000),
  awarded_claim_id uuid references public.claims (id) on delete set null,
  escalated_to text,
  resolved_by uuid references public.profiles (id) on delete set null,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.activity_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles (id) on delete set null,
  event_code text not null check (char_length(event_code) between 2 and 12),
  action text not null check (char_length(action) between 2 and 160),
  detail text not null check (char_length(detail) between 2 and 500),
  item_id uuid references public.items (id) on delete set null,
  claim_id uuid references public.claims (id) on delete set null,
  created_at timestamptz not null default now()
);

create index items_public_feed_idx on public.items (approval_status, status, created_at desc);
create index items_reporter_idx on public.items (reporter_id, created_at desc);
create index items_category_type_idx on public.items (category_id, type, occurred_on desc);
create index claims_item_idx on public.claims (item_id, status, created_at desc);
create index claims_claimant_idx on public.claims (claimant_id, created_at desc);
create index messages_conversation_idx on public.messages (conversation_id, created_at);
create index notifications_user_idx on public.notifications (user_id, read_at, created_at desc);
create index activity_log_created_idx on public.activity_log (created_at desc);

create function private.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = (select auth.uid())
      and p.role = 'admin'
      and p.is_active
  );
$$;

create function private.owns_item(target_item_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.items i
    where i.id = target_item_id
      and i.reporter_id = (select auth.uid())
  );
$$;

create function private.can_read_item_photo(target_path text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.items i
    where i.photo_path = target_path
      and (
        i.approval_status = 'approved'
        or i.reporter_id = (select auth.uid())
        or private.is_admin()
      )
  );
$$;

create function private.is_claim_party(target_claim_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.claims c
    join public.items i on i.id = c.item_id
    where c.id = target_claim_id
      and ((select auth.uid()) = c.claimant_id or (select auth.uid()) = i.reporter_id)
  );
$$;

create function private.is_conversation_party(target_conversation_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.conversations cv
    join public.claims c on c.id = cv.claim_id
    join public.items i on i.id = c.item_id
    where cv.id = target_conversation_id
      and ((select auth.uid()) = c.claimant_id or (select auth.uid()) = i.reporter_id)
  );
$$;

revoke execute on function private.is_admin() from public;
revoke execute on function private.owns_item(uuid) from public;
revoke execute on function private.can_read_item_photo(text) from public;
revoke execute on function private.is_claim_party(uuid) from public;
revoke execute on function private.is_conversation_party(uuid) from public;
grant usage on schema private to anon, authenticated;
grant execute on function private.is_admin() to anon, authenticated;
grant execute on function private.owns_item(uuid) to authenticated;
grant execute on function private.can_read_item_photo(text) to anon, authenticated;
grant execute on function private.is_claim_party(uuid) to authenticated;
grant execute on function private.is_conversation_party(uuid) to authenticated;

create function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  inferred_name text;
  inferred_student_id text;
  inferred_role public.app_role;
begin
  inferred_name := coalesce(
    nullif(trim(new.raw_user_meta_data ->> 'full_name'), ''),
    nullif(split_part(coalesce(new.email, ''), '@', 1), ''),
    'UIU Student'
  );
  inferred_student_id := coalesce(
    nullif(trim(new.raw_user_meta_data ->> 'student_id'), ''),
    nullif(split_part(coalesce(new.email, ''), '@', 1), ''),
    new.id::text
  );
  -- Open portal: the sign-in tab picks the role, so honour it at creation.
  inferred_role := case
    when lower(coalesce(new.raw_user_meta_data ->> 'role', '')) = 'admin' then 'admin'
    else 'student'
  end::public.app_role;

  insert into public.profiles (id, full_name, department, role)
  values (
    new.id,
    inferred_name,
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'department'), ''), 'Not specified'),
    inferred_role
  );

  insert into public.profile_private (user_id, student_id, phone)
  values (
    new.id,
    inferred_student_id,
    nullif(trim(new.raw_user_meta_data ->> 'phone'), '')
  );

  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function private.handle_new_user();

create function private.validate_item_private_detail()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists (
    select 1 from public.items i
    where i.id = new.item_id and i.reporter_id = new.reporter_id
  ) then
    raise exception 'Private detail reporter must match item reporter';
  end if;
  return new;
end;
$$;

create trigger validate_item_private_detail
  before insert or update on public.item_private_details
  for each row execute function private.validate_item_private_detail();

create function private.validate_claim()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_type public.item_type;
  target_reporter uuid;
begin
  select i.type, i.reporter_id into target_type, target_reporter
  from public.items i
  where i.id = new.item_id and i.approval_status = 'approved' and i.status <> 'resolved';

  if target_type is null then
    raise exception 'Claims require an approved, unresolved item';
  end if;
  if target_reporter = new.claimant_id then
    raise exception 'A reporter cannot claim their own item';
  end if;
  if (target_type = 'found' and new.kind <> 'ownership')
     or (target_type = 'lost' and new.kind <> 'recovery') then
    raise exception 'Claim kind does not match item type';
  end if;
  return new;
end;
$$;

create trigger validate_claim
  before insert or update of item_id, claimant_id, kind on public.claims
  for each row execute function private.validate_claim();

create function private.sync_item_from_claim()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    update public.items
    set status = case
      when new.kind = 'ownership' then 'pending_claim'::public.item_status
      else 'match_under_review'::public.item_status
    end
    where id = new.item_id and status <> 'resolved';
    return new;
  end if;

  if new.status = 'returned' and old.status <> 'returned' then
    update public.items set status = 'resolved' where id = new.item_id;
  elsif new.status = 'rejected' and old.status <> 'rejected'
        and not exists (
          select 1 from public.claims c
          where c.item_id = new.item_id
            and c.id <> new.id
            and c.status in ('pending', 'approved')
        ) then
    update public.items set status = 'open' where id = new.item_id and status <> 'resolved';
  end if;

  return new;
end;
$$;

create trigger sync_item_after_claim_insert
  after insert on public.claims
  for each row execute function private.sync_item_from_claim();

create trigger sync_item_after_claim_status
  after update of status on public.claims
  for each row execute function private.sync_item_from_claim();

create function private.validate_claim_evidence()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists (
    select 1 from public.claims c
    where c.id = new.claim_id and c.claimant_id = new.claimant_id
  ) then
    raise exception 'Evidence claimant must match claim claimant';
  end if;
  return new;
end;
$$;

create trigger validate_claim_evidence
  before insert or update on public.claim_evidence
  for each row execute function private.validate_claim_evidence();

create function private.validate_item_match()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists (select 1 from public.items where id = new.lost_item_id and type = 'lost')
     or not exists (select 1 from public.items where id = new.found_item_id and type = 'found') then
    raise exception 'Match must connect one lost item and one found item';
  end if;
  return new;
end;
$$;

create trigger validate_item_match
  before insert or update on public.item_matches
  for each row execute function private.validate_item_match();

create function private.validate_conversation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists (
    select 1 from public.claims c
    where c.id = new.claim_id and c.item_id = new.item_id and c.status = 'approved'
  ) then
    raise exception 'Conversation requires an approved claim for this item';
  end if;
  return new;
end;
$$;

create trigger validate_conversation
  before insert or update on public.conversations
  for each row execute function private.validate_conversation();

create function private.guard_item_update()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if current_user in ('postgres', 'service_role', 'supabase_admin')
     or private.is_admin() then
    return new;
  end if;

  if old.reporter_id <> (select auth.uid())
     or old.approval_status <> 'pending'
     or new.approval_status <> 'pending' then
    raise exception 'Users may only edit their own pending submissions';
  end if;

  new.reporter_id = old.reporter_id;
  new.status = old.status;
  new.reviewed_by = old.reviewed_by;
  new.reviewed_at = old.reviewed_at;
  new.rejection_reason = old.rejection_reason;
  new.created_at = old.created_at;
  return new;
end;
$$;

create trigger guard_item_update
  before update on public.items
  for each row execute function private.guard_item_update();

create function private.guard_handover_update()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if current_user in ('postgres', 'service_role', 'supabase_admin')
     or private.is_admin() then
    if new.status = 'complete' and old.status <> 'complete' then
      new.completed_at = now();
      new.completed_by = (select auth.uid());
    end if;
    return new;
  end if;

  if not private.is_claim_party(old.claim_id)
     or old.status <> 'proposed'
     or new.status <> 'confirmed' then
    raise exception 'Participants may only confirm a proposed handover';
  end if;

  -- A participant can confirm, but cannot alter the PIN or handover ownership.
  new.claim_id = old.claim_id;
  new.conversation_id = old.conversation_id;
  new.location = old.location;
  new.scheduled_for = old.scheduled_for;
  new.pin_code = old.pin_code;
  new.confirmed_at = now();
  new.completed_at = old.completed_at;
  new.completed_by = old.completed_by;
  new.created_at = old.created_at;
  return new;
end;
$$;

create trigger guard_handover_update
  before update on public.handovers
  for each row execute function private.guard_handover_update();

create trigger profiles_set_updated_at before update on public.profiles
  for each row execute function private.set_updated_at();
create trigger profile_private_set_updated_at before update on public.profile_private
  for each row execute function private.set_updated_at();
create trigger categories_set_updated_at before update on public.categories
  for each row execute function private.set_updated_at();
create trigger items_set_updated_at before update on public.items
  for each row execute function private.set_updated_at();
create trigger item_private_details_set_updated_at before update on public.item_private_details
  for each row execute function private.set_updated_at();
create trigger claims_set_updated_at before update on public.claims
  for each row execute function private.set_updated_at();
create trigger claim_evidence_set_updated_at before update on public.claim_evidence
  for each row execute function private.set_updated_at();
create trigger item_matches_set_updated_at before update on public.item_matches
  for each row execute function private.set_updated_at();
create trigger conversations_set_updated_at before update on public.conversations
  for each row execute function private.set_updated_at();
create trigger handovers_set_updated_at before update on public.handovers
  for each row execute function private.set_updated_at();
create trigger disputes_set_updated_at before update on public.disputes
  for each row execute function private.set_updated_at();

